### ISSUE TITLE
Scroll state is not reset when changing page

### ISSUE THREAD

**Issue by petervelosy** [sproctor/compose-data-table#16]
When you scroll down on one page and change page using the controls on the bottom, the scroll state is not reset.
This can cause the second page to look seemingly empty, whereas in reality, the items on it are located under the header and can be revealed using a scroll down gesture.

**Comment by sproctor** [comment]
I guess the scroll state should be keyed to the index. I'll look into this later today.

**Comment by sproctor** [comment]
Sorry for the delay here. Something came up and I didn't have a chance to get back to this issue. It's fixed in commit e2ab26b4eee1b5de521e6fd1eec1ab3faae9a1e9
