### ISSUE TITLE
Allow lazy fetching in PaginatedDataTable

### ISSUE THREAD

**Issue by petervelosy** [sproctor/compose-data-table#17]
When using a PaginatedDataTable, it should be possible to fetch the contents of one page only at a time.

**Comment by sproctor** [comment]
This is out of the scope of what I'm willing to do. Currently the columns are sized by all the rows, so the table doesn't resize as you page through. If you want to implement this as a third table type, I'd merge it.

**Comment by sproctor** [comment]
Sorry, I've been out of town for a while and I didn't notice the PR. Actually, having it as a completely separate component like that makes sense. I'm going to add some comments to the PR.

**Comment by sproctor** [comment]
Nevermind, it was simpler to just make the changes that I wanted than to comment the PR. I changed PaginatedDataTableState to store the count, and removed the lazy version.
