### ISSUE TITLE
Allow scrolling horizontally

### ISSUE THREAD

**Issue by hasanelfalakiy** [sproctor/compose-data-table#19]
Can the table be scrolled horizontally?

**Comment by sproctor** [comment]
Currently, no. It's something I plan to implement eventually. It should be relatively simple to add to the state.

**Comment by hasanelfalakiy** [comment]
> Currently, no. It's something I plan to implement eventually. It should be relatively simple to add to the state.

okay

**Comment by sproctor** [comment]
This is implemented in commit 39304f654ad8d7ff7829a9130561aaad3ff554cf and it will be in the next release.

**Comment by gdude2002** [comment]
While this appears to be possible as per the update demo, it appears the glue code required to wrap this library's scrolling states hasn't actually been included with the library, and only exists in the demo - [these functions](https://github.com/sproctor/compose-data-table/blob/main/demo-common/src/commonMain/kotlin/com/seanproctor/datatable/demo/Scrollbar.kt) and their platform-specific implementations, for example.

 Is there any chance this will be changed?
