### ISSUE TITLE
Pagination count is wrong

### ISSUE THREAD

**Issue by szsoftware** [sproctor/compose-data-table#6]
Hey, I just imported the project and have still a hustle with the multiplatform thing.

Can't provide a patch but a quick shot:

`val scope = PaginatedRowScope(start, start + state.pageSize, this)`

should rather be

`val scope = PaginatedRowScope(start, start + state.pageSize -1, this) `

or something like that.

**Comment by sproctor** [comment]
Thanks. Fixed in 71cc1a3
